export const UPDATE_DURATION = 'UPDATE_DURATION';
export const UPDATE_SOUND_TYPE = 'UPDATE_SOUND_TYPE';
export const UPDATE_OCTAVE = 'UPDATE_OCTAVE';
export const ADD_PLAYING_KEY = 'ADD_PLAYING_KEY';
export const REMOVE_PLAYING_KEY = 'REMOVE_PLAYING_KEY';
